version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 3001:3001
    networks:
      - mlnetwork
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - mlnetwork
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  mlnetwork:
    driver: bridge
